import { glob } from "astro/loaders";
import { defineCollection } from "astro:content";
import { z } from "astro:schema";

// Schema para Productos
const productsCollection = defineCollection({
  loader: glob({ pattern: "**/*.md", base: "./src/content/products" }),
  schema: z.object({
    productId: z.string(),
    asin: z.string(),
    lang: z.enum(["es", "en"]),

    title: z.string(),
    brand: z.string(),
    model: z.string().optional(),
    description: z.string(),
    shortDescription: z.string(),

    category: z.string(),
    subcategory: z.string().optional(),
    tags: z.array(z.string()),

    price: z.number(),
    originalPrice: z.number().optional(),
    currency: z.enum(["EUR", "USD"]).default("EUR"),
    affiliateUrl: z.string().url(),

    rating: z.number().min(0).max(5),
    totalReviews: z.number().default(0),
    ourRating: z.number().min(0).max(10).optional(),

    pros: z.array(z.string()),
    cons: z.array(z.string()),
    specifications: z.record(z.string(), z.string()).optional(),

    featuredImage: z.object({
      url: z.string(),
      alt: z.string(),
    }),
    gallery: z.array(z.object({
      url: z.string(),
      alt: z.string(),
    })).optional(),

    // 3D Model (generated by Tripo3D)
    model3dUrl: z.string().optional(),

    status: z.enum(["draft", "published", "archived"]).default("published"),
    isFeatured: z.boolean().default(false),
    isOnSale: z.boolean().default(false),
    publishedAt: z.coerce.date(),
    updatedAt: z.coerce.date(),

    relatedProducts: z.array(z.string()).optional(),
  }),
});

export const collections = {
  products: productsCollection,
};
